name: Deploy Frontend

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger VPS Webhook
        run: |
          curl -X POST http://vps1.hype-lab.cloud:3001/deploy/frontend \
          -H "x-deploy-token: dinar-cicd-secret-123"
